### ISSUE TITLE
MySQL support

### ISSUE THREAD

**Issue by zellyn** [src-d/go-kallax#128]
Just curious: are there plans to make kallax support MySQL? Our organization is tied to MySQL for operational reasons.

**Comment by delaneyj** [comment]
Same question for SQLite

**Comment by erizocosmico** [comment]
Right now, there are no future plans to add support for any other database systems from our side. We would accept this addition if someone decides to do a pull request implementing support for other databases, though. I don't think it would be an easy change, it was initially designed to work only with PostgreSQL and might be too tied to it.

**Comment by joeblew99** [comment]
Could you elaborate on why ?

I wrote a similar system to this to access oracle DBs many years ago and it's pretty similar to your design. I only supported stored procedures though.

So here is what i would assume :
The patterns you use are pretty cross dB. Like the way you manage relationships, etc. 
The templates are definitely definitely not.

**Comment by erizocosmico** [comment]
Off the top of my head, these would be not so easy problems that we'd come across expanding support for more databases. There's probably more.

* Schema generation generates JSON field accessors that are only usable in PostgreSQL. Ideally, it would have to work out of the box with any database without any change in the generated code. That means some parts that were not aware of the database being used need to be.
* Same with the support for slices and arrays of all basic go types, most of which are not implemented by us because they're already supported by the [postgres driver](https://github.com/lib/pq).
* Same with JSON support, if the database does not support JSON we should avoid JSON fields altogether or handle them just as blobs or something.
* Not all databases have the same operators (the most easy to solve problem, though). Would need a set of base operators supported on all of them and then db-specific ones in their own packages.

It's not an impossible change, it just wasn't designed with other systems in mind, so it may need a lot of internal changes. It can be done, we just can't invest the time to implement it at the moment. Maybe in the future we can. And, of course, if someone contributed said support for X database we'd be happy to accept it and integrate it.
We would also be happy accepting changes to allow extending kallax for database X by third parties without having to be necessarily in the core.

**Comment by joeblew99** [comment]
Thanks for the explanation.
I am going to play around with this.
I guess Proteus is going to work with this.

Have you thought about message queue integration yet ?

Here's where i am at:
I use protobuf as my source of truth to codegen from.
Go-kit for transport and binding. This allows me more transport options.
It codegen all the code Proteus does but allows me to hook into NATS, in that everything coming through the RPC layer hits NATS and goes back up through RPC layer to clients.
Then there is the storage layer. I decided to use nosql and materialised views for a cqrs architecture. boltdb, minio, rook, bleve. Any types coming in through Nat's go into whatever storage layer that makes sense.
Data storage views are materialised in the various storage layer and the meta describing it is derived from protobuf annotations. 
This allows clients to also do caching of data on their side and get their cache automatically updated via the event stream flowing out to them.

Data migration is not used at all. Instead like in cqrs and blockchainy architecture all data in the stores can be deleted and the event store is used to recreate all of it again.

**Comment by erizocosmico** [comment]
While we internally might use proteus along with this, they are going to be kept completely separated, so I don't think we'll do anything special for it in this specific library.

**Comment by joeblew99** [comment]
@erizocosmico thanks for the feedback.

I dont think i will use this lib. I need something more flexible because i need to run the DB on clients and Servers, and so a KV store suits me better

**Comment by erizocosmico** [comment]
Will close this for now.

**Comment by jirfag** [comment]
Hello, @zellyn @delaneyj @joeblew99 @smola @erizocosmico 
This amazing ORM and GORM inspired us to create typesafe ORM, that supports MySQL, PostgreSQL, Sqlite3, SQL Server. You can find it [here](https://github.com/jirfag/go-queryset/tree/master). Hope it will be helpful.
