### ISSUE TITLE
With*() Query does not work with Count()

### ISSUE THREAD

**Issue by Niondir** [src-d/go-kallax#205]
`store.Count(model.NewDeviceQuery().WithCustomer())` results in `pq: Spaltenverweis „id“ ist nicht eindeutig`

Is this intended, or should the With* part be ignored during `Count()`

**Comment by erizocosmico** [comment]
Can you paste the output changing `store.Count` by `store.Debug().Count`? It's definitely not by design.

**Comment by erizocosmico** [comment]
Just tried this and it worked for me. Maybe it's because it's trying to do `COUNT(identifier)`. Changed it to `COUNT(alias.*)` and now it should work. I'm gonna make a new release. Tell me if that solves it for you.

Note that adding `With*` to a query does not change the result of the `Count` since this is a left join and the result will always be the number of devices in your case no matter if they have a customer or not.
