### ISSUE TITLE
`kallax migrate` should create output folder if not exists

### ISSUE THREAD

**Issue by jBugman** [src-d/go-kallax#223]
For example, given only folder `db` is present, but not `migrations`, command
`kallax migrate --input ./model/ --out ./db/migrations` will silently do nothing. It should create intermediate folders and proceed, or at least return an error.

**Comment by roobre** [comment]
Since #225 is already fixed, these errors should not be silent anymore. Automatically creating these dirs could be potentially dangerous for certain scenarios.

Since the error `kallax: cannot check if `dir` is a directory: stat ./migrations: no such file or directory` is verbose enough for me, I don't see any reason to create this directory automatically.
