### ISSUE TITLE
Query().WithAll()

### ISSUE THREAD

**Issue by Niondir** [src-d/go-kallax#232]
When loading one entity and changing some value, the `store.Update()` method will delete all relations that are not loaded. Therefore one has to explicitly call all `With**()` methods. 

If there isn't some other way to load an entity with all relations, or to save an entity without setting all relation to `null` I would suggest some method `New**Query().WithAll()` to load all related entities as well.

**Comment by roobre** [comment]
Relations being deleted when set to `nil` is actually a bug and not expected behaviour, as seen in related issues (https://github.com/src-d/go-kallax/issues/211). This should have been fixed with https://github.com/src-d/go-kallax/pull/214, but for some reason it's back to haunt us. I guess we'll need to wait for a fix.

As a workaraound, I just feed `Update()` the name of the fields I want to update explicitly.

**Comment by roobre** [comment]
Querying all relationships at once is probably a bad idea on most cases, so it makes no sense to me to expose this functionality that easy. Users willing to do this can easily chain all `WithTYPE` functions.

**Comment by Niondir** [comment]
It's definitely more about the saving part that must not set the not queried relations to nil.

**Comment by roobre** [comment]
The issue you mention (#211) has already been fixed (https://github.com/src-d/go-kallax/pull/214).
