### ISSUE TITLE
Current status of Kallax

### ISSUE THREAD

**Issue by llonchj** [src-d/go-kallax#297]
I am about to start a project involving Postgres. I like kallax design compared to other Golang ORM. 

Unfortunately the project seems incomplete (i.e. m2m) and last commit is dated several months ago.

@roobre, what are the current situation and future plans of the project?

**Comment by roobre** [comment]
Hello,

Thanks for your interest in kallax. Right now I'm not being able to give the project all the time I'd like, since I'm no longer using `kallax` as a part of any professional project. However, I try my best to get bugs fixed and PRs merged. Regarding m2m, as well as other unimplemented major features, I'm afraid they won't be coming in the near future, at least not from me. Of course if anyone in the community want to give them a try and submit a PR, it will be reviewed and accepted if the review is successful, but for the moment I can't promise anything else.

My advice is to use `kallax` if you feel it fits your needs on its current state. Otherwise, take a look at `sqlboiler` (its approach is different from most ORMs, but its quite complete right now) or write your own queries and map them to your structs with `pg`.

**Comment by llonchj** [comment]
Gracias @roobre!
